DELETE from birds;

INSERT INTO birds (species_code, scientific_name, english_name, french_name)
VALUES
('eurmag1', 'Pica pica', 'Eurasian Magpie', 'Pie bavarde'),
('bltacc1', 'Prunella atrogularis', 'Black-throated Accentor', 'Accenteur à gorge noire'),
('alpacc1', 'Prunella collaris', 'Alpine Accentor', 'Accenteur alpin'),
('dunnoc1', 'Prunella modularis', 'Dunnock', 'Accenteur mouchet'), 
('rutscr1', 'Cercotrichas galactotes', 'Rufous-tailed Scrub-Robin', 'Agrobate roux'), 
('booeag1', 'Hieraaetus pennatus', 'Booted Eagle', 'Aigle botté'), 
('grseag1', 'Clanga clanga', 'Greater Spotted Eagle', 'Aigle criard'), 
('boneag2', 'Aquila fasciata', 'Bonelli''s Eagle', 'Aigle de Bonelli'), 
('steeag1', 'Aquila nipalensis', 'Steppe Eagle', 'Aigle des steppes'),
('spaeag1', 'Aquila adalberti', 'Spanish Eagle', 'Aigle ibérique'), 
('impeag1', 'Aquila heliaca', 'Imperial Eagle', 'Aigle impérial'),
('whisto1', 'Ciconia ciconia', 'White Stork', 'Cigogne blanche'), 
('whoswa', 'Cygnus cygnus', 'Whooper Swan', 'Cygne chanteur'), 
('grefla3', 'Phoenicopterus roseus', 'Greater Flamingo', 'Flamant rose'), 
('kumgul1', 'Larus glaucoides kumlieni', 'Iceland Gull (kumlieni)', 'Goéland arctique (kumlieni)'),
('blhher1', 'Ardea melanocephala', 'Black-headed Heron', 'Héron mélanocéphale'), 
('comkin1', 'Alcedo atthis', 'Common Kingfisher', 'Martin-pêcheur d''Europe'), 
('litswi1', 'Apus affinis', 'Little Swift', 'Martinet des maisons'),
('eurbla', 'Turdus merula', 'Eurasian Blackbird', 'Merle noir'), 
('lottit1', 'Aegithalos caudatus', 'Long-tailed Tit', 'Orite à longue queue'), 
('houspa', 'Passer domesticus','House Sparrow', 'Moineau domestique'),
('grswoo', 'Dendrocopos major', 'Great Spotted Woodpecker', 'Pic épeiche'), 
('eugwoo2', 'Picus viridis', 'Eurasian Green Woodpecker', 'Pic vert'), 
('rocpig', 'Columba livia', 'Rock Pigeon', 'Pigeon biset'), 
('cowpig1', 'Columba palumbus', 'Common Wood-Pigeon', 'Pigeon ramier'),
('razorb', 'Alca torda', 'Razorbill', 'Pingouin torda'),
('comnig1', 'Luscinia megarhynchos', 'Common Nightingale', 'Rossignol philomèle'),
('waldra1', 'Geronticus eremita', 'Northern Bald Ibis', 'Ibis chauve'),
('gretit1', 'Parus major', 'Great Tit', 'Mésange charbonnière');
