DELETE from birds;

INSERT INTO birds (species_code, scientific_name, common_name)
VALUES
('eurmag1', 'Pica pica', 'Pie bavarde'),
('bltacc1', 'Prunella atrogularis', 'Accenteur à gorge noire'),
('alpacc1', 'Prunella collaris', 'Accenteur alpin'),
('dunnoc1', 'Prunella modularis', 'Accenteur mouchet'), 
('rutscr1', 'Cercotrichas galactotes', 'Agrobate roux'), 
('booeag1', 'Hieraaetus pennatus', 'Aigle botté'), 
('grseag1', 'Clanga clanga', 'Aigle criard'), 
('boneag2', 'Aquila fasciata', 'Aigle de Bonelli'), 
('steeag1', 'Aquila nipalensis', 'Aigle des steppes'),
('spaeag1', 'Aquila adalberti', 'Aigle ibérique'), 
('impeag1', 'Aquila heliaca', 'Aigle impérial'),
('whisto1', 'Ciconia ciconia', 'Cigogne blanche'), 
('whoswa', 'Cygnus cygnus', 'Cygne chanteur'), 
('grefla3', 'Phoenicopterus roseus', 'Flamant rose'), 
('kumgul1', 'Larus glaucoides kumlieni', 'Goéland arctique (kumlieni)'),
('blhher1', 'Ardea melanocephala', 'Héron mélanocéphale'), 
('comkin1', 'Alcedo atthis', 'Martin-pêcheur d''Europe'), 
('litswi1', 'Apus affinis', 'Martinet des maisons'),
('eurbla', 'Turdus merula', 'Merle noir'), 
('lottit1', 'Aegithalos caudatus', 'Orite à longue queue'), 
('houspa', 'Passer domesticus', 'Moineau domestique'),
('grswoo', 'Dendrocopos major', 'Pic épeiche'), 
('eugwoo2', 'Picus viridis', 'Pic vert'), 
('rocpig', 'Columba livia', 'Pigeon biset'), 
('cowpig1', 'Columba palumbus', 'Pigeon ramier'),
('razorb', 'Alca torda', 'Pingouin torda'),
('comnig1', 'Luscinia megarhynchos', 'Rossignol philomèle'),
('waldra1', 'Geronticus eremita', 'Ibis chauve'),
('gretit1', 'Parus major', 'Mésange charbonnière');