DELETE from birds;

INSERT INTO birds (species_code, scientific_name)
VALUES
('eurmag1', 'Pica pica'),
('bltacc1', 'Prunella atrogularis'),
('alpacc1', 'Prunella collaris'),
('dunnoc1', 'Prunella modularis'), 
('rutscr1', 'Cercotrichas galactotes'), 
('booeag1', 'Hieraaetus pennatus'), 
('grseag1', 'Clanga clanga'), 
('boneag2', 'Aquila fasciata'), 
('steeag1', 'Aquila nipalensis'),
('spaeag1', 'Aquila adalberti'), 
('impeag1', 'Aquila heliaca'),
('whisto1', 'Ciconia ciconia'), 
('whoswa', 'Cygnus cygnus'), 
('grefla3', 'Phoenicopterus roseus'), 
('kumgul1', 'Larus glaucoides kumlieni'),
('blhher1', 'Ardea melanocephala'), 
('comkin1', 'Alcedo atthis'), 
('litswi1', 'Apus affinis'),
('eurbla', 'Turdus merula'), 
('lottit1', 'Aegithalos caudatus'), 
('houspa', 'Passer domesticus'),
('grswoo', 'Dendrocopos major'), 
('eugwoo2', 'Picus viridis'), 
('rocpig', 'Columba livia'), 
('cowpig1', 'Columba palumbus'),
('razorb', 'Alca torda'),
('comnig1', 'Luscinia megarhynchos'),
('waldra1', 'Geronticus eremita'),
('gretit1', 'Parus major');
